version: "3.9"
services:
  database:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./.env
    ports:
      - ":5432"
    restart:
      always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - ":8000"
    restart:
      always
    depends_on:
      - database

  nginx:
    image: nginx:1.25.3-alpine3.18
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - app

volumes:
  postgres_data: