"""04_login_unique

Revision ID: 208763c4427a
Revises: d1457fdd1129
Create Date: 2024-03-24 19:47:52.816226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208763c4427a'
down_revision: Union[str, None] = 'd1457fdd1129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
