"""03_short_url_unique_fild_change

Revision ID: 300d8a60b882
Revises: 503c9a623c61
Create Date: 2023-11-16 21:36:34.613999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300d8a60b882'
down_revision: Union[str, None] = '503c9a623c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('short_url', sa.Column('shorted', sa.String(), nullable=True))
    op.add_column('short_url', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('short_url_origin_url_key', 'short_url', type_='unique')
    op.drop_constraint('short_url_shorted_url_key', 'short_url', type_='unique')
    op.create_index(op.f('ix_short_url_created_at'), 'short_url', ['created_at'], unique=False)
    op.create_unique_constraint(None, 'short_url', ['shorted'])
    op.drop_column('short_url', 'origin_url')
    op.drop_column('short_url', 'shorted_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('shorted_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_url', sa.Column('origin_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'short_url', type_='unique')
    op.drop_index(op.f('ix_short_url_created_at'), table_name='short_url')
    op.create_unique_constraint('short_url_shorted_url_key', 'short_url', ['shorted_url'])
    op.create_unique_constraint('short_url_origin_url_key', 'short_url', ['origin_url'])
    op.drop_column('short_url', 'created_at')
    op.drop_column('short_url', 'shorted')
    op.drop_column('short_url', 'origin')
    # ### end Alembic commands ###
