"""02_added-short-url-statistic

Revision ID: 503c9a623c61
Revises: 0f8377719863
Create Date: 2023-11-08 17:29:08.151195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503c9a623c61'
down_revision: Union[str, None] = '0f8377719863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url_statistic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follow_count', sa.Integer(), nullable=True),
    sa.Column('last_ip_follow', sa.String(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['short_url.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_statistic_id'), 'short_url_statistic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_statistic_id'), table_name='short_url_statistic')
    op.drop_table('short_url_statistic')
    # ### end Alembic commands ###
